## Linear Regression

### Added snippet used as a reference for all models

This model is based on the TuringTutorial example [LinearRegression](https://github.com/TuringLang/TuringTutorials/blob/csp/linear/LinearRegression.ipynb) by Cameron Pfiffer.

Turing is powerful when applied to complex hierarchical models, but it can also be put to task at common statistical procedures, like linear regression. This tutorial covers how to implement a linear regression model in Turing.

We begin by importing all the necessary libraries.

In [1]:
using StatisticalRethinking, CmdStan, StanMCMCChains, GLM
gr(size=(500,500))

ProjDir = rel_path("..", "scripts", "00")
cd(ProjDir)

Import the dataset.

In [2]:
howell1 = CSV.read(rel_path("..", "data", "Howell1.csv"), delim=';')
df = convert(DataFrame, howell1);

Use only adults

In [3]:
data = filter(row -> row[:age] >= 18, df)

352×4 DataFrame
│ Row │ height   │ weight   │ age      │ male   │
│     │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Int64⍰ │
├─────┼──────────┼──────────┼──────────┼────────┤
│ 1   │ 151.765  │ 47.8256  │ 63.0     │ 1      │
│ 2   │ 139.7    │ 36.4858  │ 63.0     │ 0      │
│ 3   │ 136.525  │ 31.8648  │ 65.0     │ 0      │
│ 4   │ 156.845  │ 53.0419  │ 41.0     │ 1      │
│ 5   │ 145.415  │ 41.2769  │ 51.0     │ 0      │
│ 6   │ 163.83   │ 62.9926  │ 35.0     │ 1      │
│ 7   │ 149.225  │ 38.2435  │ 32.0     │ 0      │
⋮
│ 345 │ 146.05   │ 39.4058  │ 37.4     │ 0      │
│ 346 │ 156.21   │ 41.0501  │ 53.0     │ 1      │
│ 347 │ 152.4    │ 40.8233  │ 49.0     │ 0      │
│ 348 │ 162.56   │ 47.0318  │ 27.0     │ 0      │
│ 349 │ 142.875  │ 34.2462  │ 31.0     │ 0      │
│ 350 │ 162.56   │ 52.1631  │ 31.0     │ 1      │
│ 351 │ 156.21   │ 54.0625  │ 21.0     │ 0      │
│ 352 │ 158.75   │ 52.5316  │ 68.0     │ 1      │

Show the first six rows of the dataset.

In [4]:
first(data, 6)

6×4 DataFrame
│ Row │ height   │ weight   │ age      │ male   │
│     │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Int64⍰ │
├─────┼──────────┼──────────┼──────────┼────────┤
│ 1   │ 151.765  │ 47.8256  │ 63.0     │ 1      │
│ 2   │ 139.7    │ 36.4858  │ 63.0     │ 0      │
│ 3   │ 136.525  │ 31.8648  │ 65.0     │ 0      │
│ 4   │ 156.845  │ 53.0419  │ 41.0     │ 1      │
│ 5   │ 145.415  │ 41.2769  │ 51.0     │ 0      │
│ 6   │ 163.83   │ 62.9926  │ 35.0     │ 1      │

The next step is to get our data ready for testing. We'll split the mtcars dataset into two subsets, one for training our model and one for evaluating our model. Then, we separate the labels we want to learn (MPG, in this case) and standardize the datasets by subtracting each column's means and dividing by the standard deviation of that column.

The resulting data is not very familiar looking, but this standardization process helps the sampler converge far easier. We also create a function called unstandardize, which returns the standardized values to their original form. We will use this function later on when we make predictions.

Split our dataset 70%/30% into training/test sets.

In [5]:
n = size(data, 1)
test_ind = sample(1:n, Int(floor(0.3*n)), replace=false);
train_ind = [(i) for i=1:n if !(i in test_ind)];
test = data[test_ind, :];
train = data[train_ind, :];

Save dataframe versions of our dataset.

In [6]:
train_cut = DataFrame(train)
test_cut = DataFrame(test)

105×4 DataFrame
│ Row │ height   │ weight   │ age      │ male   │
│     │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Int64⍰ │
├─────┼──────────┼──────────┼──────────┼────────┤
│ 1   │ 147.955  │ 39.3775  │ 30.0     │ 0      │
│ 2   │ 151.765  │ 42.8644  │ 49.0     │ 1      │
│ 3   │ 156.845  │ 47.6272  │ 31.0     │ 1      │
│ 4   │ 144.78   │ 38.045   │ 29.0     │ 0      │
│ 5   │ 158.75   │ 48.6761  │ 28.0     │ 1      │
│ 6   │ 153.035  │ 49.89    │ 88.0     │ 1      │
│ 7   │ 147.32   │ 35.9472  │ 40.0     │ 0      │
⋮
│ 98  │ 165.735  │ 58.5984  │ 42.0     │ 1      │
│ 99  │ 161.29   │ 47.854   │ 35.0     │ 1      │
│ 100 │ 151.13   │ 43.9701  │ 26.0     │ 1      │
│ 101 │ 170.815  │ 59.7607  │ 33.0     │ 1      │
│ 102 │ 167.005  │ 50.6039  │ 49.0     │ 1      │
│ 103 │ 151.943  │ 43.7149  │ 21.0     │ 1      │
│ 104 │ 147.955  │ 49.8951  │ 19.0     │ 0      │
│ 105 │ 168.275  │ 56.047   │ 21.0     │ 1      │

Create our labels. These are the values we are trying to predict.

In [7]:
train_label = train[:, :height]
test_label = test[:, :height]

105-element Array{Union{Missing, Float64},1}:
 147.955 
 151.765 
 156.845 
 144.78  
 158.75  
 153.035 
 147.32  
 162.56  
 157.48  
 163.83  
   ⋮     
 151.765 
 165.735 
 161.29  
 151.13  
 170.815 
 167.005 
 151.9428
 147.955 
 168.275 

Get the list of columns to keep.

In [8]:
remove_names = filter(x->!in(x, [:height, :age, :male]), names(data))

1-element Array{Symbol,1}:
 :weight

Filter the test and train sets.

In [9]:
train = Matrix(train[:, remove_names]);
test = Matrix(test[:, remove_names]);

A handy helper function to rescale our dataset.

In [10]:
function standardize(x)
    return (x .- mean(x, dims=1)) ./ std(x, dims=1), x
end

standardize (generic function with 1 method)

Another helper function to unstandardize our datasets.

In [11]:
function unstandardize(x, orig)
    return x .* std(orig, dims=1) .+ mean(orig, dims=1)
end

unstandardize (generic function with 1 method)

Standardize our dataset.

In [12]:
(train, train_orig) = standardize(train)
(test, test_orig) = standardize(test)
(train_label, train_l_orig) = standardize(train_label)
(test_label, test_l_orig) = standardize(test_label);

Design matrix

In [13]:
dmat = [ones(size(train, 1)) train]

247×2 Array{Float64,2}:
 1.0  -1.94617  
 1.0   1.29774  
 1.0  -0.504436 
 1.0   2.82198  
 1.0  -0.969093 
 1.0   1.6712   
 1.0  -1.48586  
 1.0   0.81571  
 1.0  -0.513121 
 1.0  -1.30781  
 ⋮              
 1.0   1.24128  
 1.0  -0.938695 
 1.0  -0.269937 
 1.0  -0.0528074
 1.0  -0.995148 
 1.0  -0.0832055
 1.0   0.507386 
 1.0  -0.573918 
 1.0  -1.5814   

Bayesian linear regression.

In [14]:
lrmodel = "
data {
  int N; //the number of observations
  int K; //the number of columns in the model matrix
  real y[N]; //the response
  matrix[N,K] X; //the model matrix
}
parameters {
  vector[K] beta; //the regression parameters
  real sigma; //the standard deviation
}
transformed parameters {
  vector[N] linpred;
  linpred <- X*beta;
}
model {
  beta[1] ~ cauchy(0,10); //prior for the intercept following Gelman 2008

  for(i in 2:K)
   beta[i] ~ cauchy(0,2.5);//prior for the slopes following Gelman 2008

  y ~ normal(linpred,sigma);
}
";

Define the Stanmodel and set the output format to :mcmcchains.

In [15]:
stanmodel = Stanmodel(name="linear_regression",
  monitors = ["beta.1", "beta.2", "sigma"],
  model=lrmodel);
# Input data for cmdstan
lrdata = Dict("N" => size(train, 1), "K" => size(dmat, 2), "y" => train_label, "X" => dmat);


File /Users/rob/.julia/dev/StatisticalRethinking/scripts/00/tmp/linear_regression.stan will be updated.



Sample using cmdstan

In [16]:
rc, sim, cnames = stan(stanmodel, lrdata, ProjDir, diagnostics=false,
  summary=false, CmdStanDir=CMDSTAN_HOME);
# Convert to a  Chain object
cnames = ["alpha", "beta[1]", "sigma"]
chain = convert_a3d(sim, cnames, Val(:mcmcchains))

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: normal_lpdf: Scale parameter is -1853.25, but must be > 0!  (in '/Users/rob/.julia/dev/StatisticalRethinking/scripts/00/tmp/linear_regression.stan' at line 21)

If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: normal_lpdf: Scale parameter is -34.2365, but must be > 0!  (in '/Users/rob/.julia/dev/StatisticalRethinking/scripts/00/tmp/linear_regression.stan' at line 21)

If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be ei

Object of type Chains, with data of type 1000×3×4 Array{Float64,3}

Log evidence      = 0.0
Iterations        = 1:1000
Thinning interval = 1
Chains            = 1, 2, 3, 4
Samples per chain = 1000
internals         = 
parameters        = alpha, beta[1], sigma

parameters
         Mean    SD   Naive SE  MCSE   ESS
  alpha 0.0000 0.0413   0.0007 0.0006 1000
beta[1] 0.7704 0.0412   0.0007 0.0007 1000
  sigma 0.6411 0.0293   0.0005 0.0005 1000



Describe the chains.

In [17]:
describe(chain)

Log evidence      = 0.0
Iterations        = 1:1000
Thinning interval = 1
Chains            = 1, 2, 3, 4
Samples per chain = 1000
parameters        = alpha, beta[1], sigma

Empirical Posterior Estimates
────────────────────────────────────────────
parameters
         Mean    SD   Naive SE  MCSE   ESS
  alpha 0.0000 0.0413   0.0007 0.0006 1000
beta[1] 0.7704 0.0412   0.0007 0.0007 1000
  sigma 0.6411 0.0293   0.0005 0.0005 1000

Quantiles
────────────────────────────────────────────
parameters
          2.5%   25.0%   50.0%  75.0%  97.5%
  alpha -0.1420 -0.0282 0.0001 0.0276 0.1484
beta[1]  0.5890  0.7427 0.7706 0.7982 0.9059
  sigma  0.5442  0.6214 0.6397 0.6597 0.7566



Perform multivariate OLS.

In [18]:
ols = lm(@formula(height ~ weight), train_cut)

StatsModels.DataFrameRegressionModel{GLM.LinearModel{GLM.LmResp{Array{Float64,1}},GLM.DensePredChol{Float64,LinearAlgebra.Cholesky{Float64,Array{Float64,2}}}},Array{Float64,2}}

Formula: height ~ 1 + weight

Coefficients:
             Estimate Std.Error t value Pr(>|t|)
(Intercept)   113.226   2.19564 51.5688   <1e-99
weight       0.922374 0.0487447 18.9226   <1e-49


Store our predictions in the original dataframe.

In [19]:
train_cut.OLSPrediction = predict(ols);
test_cut.OLSPrediction = predict(ols, test_cut);

Make a prediction given an input vector.

In [20]:
function prediction(chain, x)
    α = chain.value[:, 1, :];
    β = [chain.value[:, i, :] for i in 2:2];
    return  mean(α) .+ x * mean.(β)
end

prediction (generic function with 1 method)

Calculate the predictions for the training and testing sets.

In [21]:
train_cut.BayesPredictions = unstandardize(prediction(chain, train), train_l_orig);
test_cut.BayesPredictions = unstandardize(prediction(chain, test), test_l_orig);

Show the first side rows of the modified dataframe.

In [22]:
remove_names = filter(x->!in(x, [:age, :male]), names(test_cut));
test_cut = test_cut[remove_names];
first(test_cut, 6)

bayes_loss1 = sum((train_cut.BayesPredictions - train_cut.height).^2);
ols_loss1 = sum((train_cut.OLSPrediction - train_cut.height).^2);

bayes_loss2 = sum((test_cut.BayesPredictions - test_cut.height).^2);
ols_loss2 = sum((test_cut.OLSPrediction - test_cut.height).^2);

println("\nTraining set:")
println("  Bayes loss: $bayes_loss1")
println("  OLS loss: $ols_loss1")

println("Test set:")
println("  Bayes loss: $bayes_loss2")
println("  OLS loss: $ols_loss2")


Training set:
  Bayes loss: 6103.089205894946
  OLS loss: 6103.088735394146
Test set:
  Bayes loss: 2951.422292024536
  OLS loss: 2961.799604807653


Plot the chains.

In [23]:
#plot(chain)

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*